Feature/sc 35723/re brand help center sub docs
opendatasoft/ods-documentation pull request #351
Opened 2022-09-22 13:20 UTC by NTerpo

2022-09-23 11:14 UTC, etienneburdet requested changes
Overall looking good! 
The shadow is interupted by the sidebar: 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/7590997/191947083-a1f0aa0c-e233-4313-baf2-7b2da4ec0765.png">
`.wy-nav-side { z-index: 100 }` seems to fix that nicely.

The language selector is still blue. 
```css
.rst-versions, 
.rst-versions .rst-current-version,
.rst-versions .rst-other-versions,
.rst-versions .rst-current-version .fa {
  background: white;
  color: black;
}

.rst-versions {
  border-top: 1px solid #DEE5EF;
}
```
Seems to fix it well.

It seems there is something that went differently in the JS build (a different node version or something), which has parts not minified and a few changes to the lock file. Seems to work though 🤷

2022-09-23 15:57 UTC, NTerpo commented on source/_themes/ods-theme/static/js/theme.js
> +var jQuery = (typeof (window) != 'undefined') ? window.jQuery : require('jquery');
I guess automatically generated.

2022-09-23 15:59 UTC, NTerpo commented on source/_themes/dev/sass/_button.sass
> +  border-radius: 4px
Let's do it then, I'll update the landing page too

2022-09-23 16:14 UTC, NTerpo commented
I've let the lang selector in blue : there were no figma for the old doc and all black & white looked a bit too sad. Otherwise I've made the fixes

2022-09-26 07:17 UTC, etienneburdet approved these changes

2022-09-26 08:27 UTC, merged